# fly.toml app configuration file generated for headlines-scraper-billowing-pine-9818 on 2024-07-31T23:02:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'headlines-scraper-billowing-pine-9818'
primary_region = 'jnb'

[build]

[env]
  PORT = '8080'
  GOOGLE_APPLICATION_CREDENTIALS = "/usr/local/bin/firebase-sa.json"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
